name: fast-myers-diff
version: 0.0.0
github: "NorfairKing/sydtest"
license: MIT
license-file: LICENSE
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2023 Tom Sydney Kerckhove"
category: Testing
synopsis: A fast implementation of the Myers diff algorithm.
description: A fast implementation of the diffing algorithm described in 'An O(ND) Difference Algorithm and Its Variations' by Eugene W. Myers.

extra-source-files:
- LICENSE

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - dlist
    - text
    - vector

tests:
  fast-myers-diff-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fast-myers-diff
    - hspec
    - text
    - vector
